const dotenv = require("dotenv");
dotenv.config();

const AI_TIMEOUT_MS = Number(process.env.AI_TIMEOUT_MS) || 20000;
const MAX_PROMPT_CHARS = Number(process.env.AI_MAX_PROMPT_CHARS) || 12000;

function truncateText(value, maxLength = MAX_PROMPT_CHARS) {
  const text = String(value || "");
  return text.length > maxLength ? `${text.slice(0, maxLength)}\n\n[Content truncated for AI request size.]` : text;
}

async function fetchWithTimeout(url, options) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), AI_TIMEOUT_MS);

  try {
    return await fetch(url, { ...options, signal: controller.signal });
  } finally {
    clearTimeout(timeout);
  }
}

function normalizeAIText(value, fallback = "No response generated by AI.") {
  const text = String(value || "").trim();
  return text || fallback;
}

function getGeminiText(data) {
  const text = data?.candidates
    ?.flatMap((candidate) => candidate?.content?.parts || [])
    ?.map((part) => part?.text)
    ?.filter(Boolean)
    ?.join("\n");

  if (text) {
    return normalizeAIText(text);
  }

  const finishReason = data?.candidates?.[0]?.finishReason;
  if (finishReason) {
    return `No text response generated by Gemini. Finish reason: ${finishReason}.`;
  }

  return "No response generated by AI.";
}

function getGeminiModelName() {
  const model = process.env.GEMINI_MODEL?.trim();
  if (!model) {
    throw new Error("GEMINI_MODEL is not configured. Set it to a supported Gemini model in the backend `.env` file.");
  }

  return model.startsWith("models/") ? model : `models/${model}`;
}

// Helper to make API requests to the LLM
async function callLLM(prompt) {
  const provider = process.env.AI_PROVIDER || "gemini";
  const safePrompt = truncateText(prompt);

  if (provider === "gemini") {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || apiKey === "your_gemini_api_key_here") {
      return "⚠️ **Gemini API Key is missing or invalid.** Please set a valid `GEMINI_API_KEY` in the backend `.env` file to enable AI capabilities.";
    }

    try {
      const modelName = getGeminiModelName();
      const response = await fetchWithTimeout(
        `https://generativelanguage.googleapis.com/v1beta/${modelName}:generateContent?key=${apiKey}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            contents: [{ parts: [{ text: safePrompt }] }],
            generationConfig: {
              temperature: 0.2,
              maxOutputTokens: 2048,
            }
          }),
        }
      );

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error?.message || "Gemini API error");
      }

      return getGeminiText(data);
    } catch (err) {
      console.error("Gemini API Request Failed:", err);
      return err.name === "AbortError"
        ? "AI service timed out. Please try again with a smaller request."
        : `AI service error: ${err.message}`;
    }
  } else if (provider === "openai") {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey || apiKey === "your_openai_api_key_here") {
      return "⚠️ **OpenAI API Key is missing or invalid.** Please set a valid `OPENAI_API_KEY` in the backend `.env` file.";
    }

    try {
      const response = await fetchWithTimeout("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${apiKey}`,
        },
        body: JSON.stringify({
          model: "gpt-4o-mini",
          messages: [{ role: "user", content: safePrompt }],
          temperature: 0.2,
          max_tokens: 2048,
        }),
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error?.message || "OpenAI API error");
      }

      return normalizeAIText(data.choices?.[0]?.message?.content);
    } catch (err) {
      console.error("OpenAI API Request Failed:", err);
      return err.name === "AbortError"
        ? "AI service timed out. Please try again with a smaller request."
        : `AI service error: ${err.message}`;
    }
  } else {
    return `Unsupported AI Provider: "${provider}". Supported values are "gemini" or "openai".`;
  }
}

// 1. AI README Generator
async function generateReadme(req, res) {
  const { repoName, description, languages = [], tags = [] } = req.body;
  if (!repoName || typeof repoName !== "string") {
    return res.status(400).json({ error: "Repository name is required." });
  }

  const prompt = `
You are a senior technical writer. Generate a professional, comprehensive, and clean GitHub README.md file for a project with the following details:
- Project Name: ${repoName}
- Description: ${description || "No description provided."}
- Languages used: ${languages.join(", ") || "Not specified"}
- Tags/Topics: ${tags.join(", ") || "Not specified"}

The README should include:
- A beautiful header with name and brief description
- Clear Features list
- Installation steps (assume standard node/npm setups unless languages dictate otherwise)
- Basic Usage examples
- Clean tables or badges where applicable
- Professional formatting in standard GitHub Flavored Markdown (do not wrap in a markdown block, just output the raw markdown text itself).
`;

  try {
  const readme = await callLLM(prompt);
    res.json({ readme });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}

// 2. AI Commit Message Generator
async function generateCommitMessage(req, res) {
  const { codeChanges, filename } = req.body;
  if (!codeChanges || typeof codeChanges !== "string") {
    return res.status(400).json({ error: "Code changes are required." });
  }

  const prompt = `
You are a helpful software engineer. Write a concise, meaningful, and professional Git commit message following conventional commits style (e.g. feat: add file explorer, fix: repair authentication token) based on these changes:
File: ${filename || "Multiple files"}
Changes/Code Diff:
${truncateText(codeChanges, 4000)}

Provide exactly ONE commit message option. Do not add explanations, quotes, bullet points, or introductory text. Just output the single-line commit message.
`;

  try {
    const commitMessage = await callLLM(prompt);
    res.json({ commitMessage: commitMessage.trim().replace(/^['"`]|['"`]$/g, "") });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}

// 3. AI Repository Description Generator
async function generateRepositoryDescription(req, res) {
  const { repoName, tags = [], languages = [] } = req.body;
  if (!repoName || typeof repoName !== "string") {
    return res.status(400).json({ error: "Repository name is required." });
  }

  const prompt = `
You are a product designer. Generate exactly THREE alternative professional, catchy, one-line project descriptions for a repository named "${repoName}" which uses these technologies: ${languages.join(", ") || "web tech"} and is tagged with: ${tags.join(", ") || "general"}.

Output only the three descriptions as a bulleted list. No introductory or concluding text.
`;

  try {
    const descriptions = await callLLM(prompt);
    res.json({ descriptions });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}

// 4. AI Repository Summary
async function summarizeRepository(req, res) {
  const { repoName, description, files = [] } = req.body;
  if (!repoName || typeof repoName !== "string") {
    return res.status(400).json({ error: "Repository name is required." });
  }

  const prompt = `
You are a senior tech lead. Analyze the structure of the repository "${repoName}".
Description: ${description || "No description provided."}
Files list:
${files.slice(0, 300).join("\n")}

Provide a high-level summary (3-4 bullet points) of the repository architecture, explaining:
- What this project is about.
- The entry points and main tech stack.
- The overall folder organization and how the parts connect.

Keep it highly technical, concise, and structured.
`;

  try {
    const summary = await callLLM(prompt);
    res.json({ summary });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}

// 5. AI Chat Assistant
async function chatAssistant(req, res) {
  const { messages, repoName, description, files = [], activeFileContext } = req.body;
  if (!Array.isArray(messages)) {
    return res.status(400).json({ error: "Messages must be an array." });
  }

  const recentMessages = messages.slice(-10);
  const safeActiveFile = activeFileContext
    ? {
        name: truncateText(activeFileContext.name, 200),
        content: truncateText(activeFileContext.content, 6000),
      }
    : null;

  // We build a context-aware system prompt
  const systemPrompt = `
You are GitHub Copilot, a senior developer AI assistant integrated into "GitHub AI", a premium MERN GitHub application.
Current Repository: ${repoName}
Repository Description: ${description || "No description provided."}
Repository Files Structure:
${files.slice(0, 300).map(f => `- ${f}`).join("\n")}

${safeActiveFile ? `Active File Open: ${safeActiveFile.name}\nActive File Code:\n\`\`\`\n${safeActiveFile.content}\n\`\`\`` : "No file is currently selected/open in the code viewer."}

Your job is to answer user queries with expert precision, provide readable code snippets, explain the workspace structure, detect bugs, or generate code/documentation.
Always reply in clean GitHub Flavored Markdown. Be concise, professional, and friendly.
`;

  // We build a chat history
  const prompt = `${systemPrompt}\n\nChat History:\n${recentMessages.map(m => `${m.role === "user" ? "User" : "Assistant"}: ${truncateText(m.content, 1500)}`).join("\n")}\n\nAssistant:`;

  try {
    const reply = await callLLM(prompt);
    res.json({ reply });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}

module.exports = {
  generateReadme,
  generateCommitMessage,
  generateRepositoryDescription,
  summarizeRepository,
  chatAssistant,
};
